### ISSUE TITLE
No supplier name on the booking page

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/edo#1420]
On https://manage-dev.happytravel.com/

**Steps.**
1. Log in some administrator;
2. open the developer panel in the browser;
3. go to to any agency and to any of its bookings;
or
4. find any booking in the Bookings menu item;
5. note the query response GET /{culture}/api/{v}/admin/bookings/{referenceCode}

**Result.**
No supplier name on the booking page. But, the response has supplier details.

**Expectations.**
The booking page in the admin panel should show the name of the supplier.

**Comment by sergeyf-QA** [comment]
**Summary:**
- now, supplier is on the booking pages.

**OK on DEV.**
