### ISSUE TITLE
Add the ability to search for agencies by ID

### ISSUE THREAD

**Issue by DenisVelinen** [happy-travel/edo#1715]
On http://manage-dev.happytravel.com/

It often happens that it's quick and convenient to find a particular agency by its ID. Unfortunately, there isn't such option. 

1. Go to Agencies page and search for an agency with ID 770 or any other.

Result.
There is no possibility to find an agency by its ID.

**Comment by AlexeyShok** [comment]
Everything is implemented on the backend. Need to add search field and filter to OData on front.
