### ISSUE TITLE
Search caching has resulted in a "reference ID is already used" error at the Columbus supplier

### ISSUE THREAD

**Issue by DenisVelinen** [happy-travel/edo#1806]
On https://dev.happytravel.com/

1. In any browser, log in with this agent
https://passbolt.happytravel.com/app/passwords/view/e7429bb6-1106-44cd-9f7b-c47df6ae43e7
2. In any other browser, log in with this agent (you can use incognito mode, but in a different browser, testing will be clearer)
https://passbolt.happytravel.com/app/passwords/view/e2d28859-a5e8-433f-a256-e8c04a3bb923
3. In both agents, do exactly the same search on the following parameters

> **Testhappytravel, Dubai, The United Arab Emirates**
> 06-08-2022 – 08-08-2022
> 1 Adult 
> RU-RU
> 

4. With any one agent make a booking
5. At another agent make the same booking

Expected.
Bookings will make in both cases.

Result.
Columbus supplier's search caching has resulted in an error
```{
    "status": 400,
    "detail": "Request to CreateReservations returned 'Error 104. Technical Error. XML reference ID is already used, please search and try again'"
}```

**Comment by sergeyf-QA** [comment]
**Summary:**
1) it is impossible to fix initial issue case
2) fixed such case only:
- In any browser, log in as the first agent
- search
Testhappytravel, Dubai, The United Arab Emirates
06-08-2022 – 08-08-2022
1 Adult
RU-RU
- book found accommodation
- In any other browser, log in as the second agent 
- do the same search
- book found accommodation


**OK on DEV.**
