### ISSUE TITLE
Error getting agency settings

### ISSUE THREAD

**Issue by nikolaeva31** [happy-travel/edo#1811]
1. Agency is verified as `readOnly` and doesn't have `ContractKind`
2. Get Agency settings 
`GET https://edo.happytravel.com/en/api/1.0/admin/agencies/357/system-settings/availability-search`

**AR**: Get error
```
{
  "status": 400,
  "detail": "ContractKind for agency is not set"
}
```

**ER**: If the agency doesn't have `FullAccess` then _GET_ method should return default settings for `ContractKind = Offline Or Credit Card`. 
_PUT_ method should return error 400 - it's impossible to change the settings for an agency that is not fully verified.

**Comment by sergeyf-QA** [comment]
**Summary:**
- now for agencies which don't have record in "AgencySystemSettings" GET 
/{culture}/api/{v}/admin/agencies/{agencyId}/system-settings/availability-search returns 
{
  "aprMode": "Hide",
  "passedDeadlineOffersMode": "Hide",
  "enabledSuppliers": null,
  "isSupplierVisible": false,
  "isDirectContractFlagVisible": false,
  "customDeadlineShift": 0
}

**OK on DEV.**
