### ISSUE TITLE
Add a re-reqest from EDO to Mapper

### ISSUE THREAD

**Issue by DenisVelinen** [happy-travel/edo#1822]
On http://happytravel.com/

On 2 June the error Request to mapper failed. Unauthorized.
Details here https://logs.happytravel.com/app/discover#/doc/d9804df0-e80f-11eb-bbd4-c3d108d86f4e/fluentd-edo-2022.06?id=kKTBJIEBHCkUScvTXYMK
In the interface, this led to no search results and an Unauthorized message (see https://happytravel.freshdesk.com/a/tickets/520).

To prevent this from happening, add a re-reqest from EDO to Mapper.

**Comment by sergeyf-QA** [comment]
impossible to test
