### ISSUE TITLE
Error when creating the card

### ISSUE THREAD

**Issue by nikolaeva31** [happy-travel/edo#1835]
1. Create a booking and try to pay

**AR**: _detail: "Method Not Allowed"_
`{"HttpRequest":{"TraceId":"0HMI5BEK67473:00000003","Method":"GET","Host":"gf-dev.happytravel.com","Path":"/api/1.0/cards","Headers":["Host: gf-dev.happytravel.com","Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkU2NTQ2QTZBQ0IxRUNDMjdBREQ3QjNENDJCNzM0MzZEMzM4NTgzQUQiLCJ0eXAiOiJhdCtqd3QiLCJ4NXQiOiI1bFJxYXNzZXpDZXQxN1BVSzNORGJUT0ZnNjAifQ.eyJuYmYiOjE2NTQ1MzY0OTcsImV4cCI6MTY1NDU0MDA5NywiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eS1kZXYuaGFwcHl0cmF2ZWwuY29tIiwiYXVkIjpbImNvbm5lY3RvcnMiLCJoaXJvc2hpbWEiLCJvZGF3YXJhIiwia29tb3JvIiwibWFwcGVyIiwic3VucHUiLCJ0c3V0c3VqaWdhc2FraSIsInZjY19zZXJ2aWNlIl0sImNsaWVudF9pZCI6ImVkbyIsImp0aSI6IkFDRTZFMTg1OThEMTUwMzU2MjdGQzMzOEQ0OUNEMzYwIiwiaWF0IjoxNjU0NTM2NDk3LCJzY29wZSI6WyJjb25uZWN0b3JzIiwiZGFjLm1hbmFnZW1lbnQiLCJrb21vcm8iLCJtYXBwZXIuZWRpdCIsIm1hcHBlci5yZWFkb25seSIsIm9kYXdhcmEudXNlcnMuZWRpdCIsInN1bnB1IiwidHN1dHN1amlnYXNha2kiLCJ2Y2MuaGlzdG9yeSIsInZjYy5pc3N1ZSJdfQ.dFkwYsddwhUehgPx14eLoQdbkJrASat8Qku6o1bHC6BMWhe883Uo3SQ_60RFOvT_tVmmNS_WAxPgHYm5hecHOfl14yreehk2TuyAqdeS94oI_kMmGk0pcVNAOGiJTVUpB973HVlaaDlCqXpXwnWc4yNbYwo3_itveXCo3RjOdPWavHOh65oJNH3u1V3dstTJyZHE1mwhN3lecazVZrI-XEnDy5CZ95Wf0023aoS1pfaWhOIzI3ee2noNGm41giz476r5ryjbZTuyJcTTTNO2SJ67f4UYmsrVbcRLNYwzMveZF5S7_aecvg8LbCzZByZ8TZYAdpkx0w6BdPw-4BzydA","Correlation-Context: ReferenceCode=DEV-HTL-AE-0003K6-01, SearchId=84c1e3ad-f06e-482f-83c8-5d812bfa204b","traceparent: 00-1780dd007ba86a9591247e86691da993-0f9278dbb3f88c51-01","x-real-ip: 192.168.3.1","x-forwarded-for: 192.168.3.1","x-forwarded-host: gf-dev.happytravel.com","x-forwarded-port: 443","x-forwarded-proto: https"],"RequestBody":""},"HttpResponse":{"StatusCode":405,"Headers":["Allow: POST"]}}`

**Comment by sergeyf-QA** [comment]
**Summary:**
- Jumeirah booking may be paid by card w/o errors

**OK on DEV.**
