### ISSUE TITLE
No notification emails are sent when a booking is Discarded

### ISSUE THREAD

**Issue by DenisVelinen** [happy-travel/edo#1853]
On https://manage-dev.happytravel.com/ and https://dev.happytravel.com/

You must have a registered administrator whose mailbox you have access to and have signed up to receive Booking Cancelled notifications.
1. Log in to the admin app and make a Discard for any booking;
2. Go to the admin mailbox and check the new mail.

Expected.
There should be an email in the admin mailbox that the booking has been discarded.

Result.
No notification email is sent when the booking is Discarded.

**Comment by sergeyf-QA** [comment]
**Summary:**
- there is an email in the admin mailbox that the booking has been discarded

**OK on DEV.**
