### ISSUE TITLE
Error with status 500 when trying to move to the third step at an agency in Read Only status

### ISSUE THREAD

**Issue by DenisVelinen** [happy-travel/edo#1886]
On https://dev.happytravel.com/

Agency in Read Only status 

> "agencyId": 1198,
> "agencyName": "The Hundred-Eighth test agency»,
> Verification State = 3
> Preferred Payment Method = 1
> Contract Kind = 0

**Expected result:**
An agency in Read Only status isn’t allowed to make bookings, but this should not result in an error with a status of 500.

**Actual result:**
Error with status 500 when trying to move to the third step at an agency in Read Only status
**Sentry ID: 4550030f689a4e5d8025c93857455347**
```
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.6.1",
    "title": "Internal Server Error",
    "status": 500,
    "detail": "Invalid value NotSpecified (Parameter 'contractKind')",
    "instance": "/en/api/1.0/accommodations/availabilities/searches/48710c87-d495-4f9c-aed4-63139413280e/results/Accommodation_12004170/room-contract-sets/cadf2e51-8107-421d-8790-4b3f250a055b",
    "spanId": "2ced67495aaa5443",
    "traceId": "58cbbeba7737e2f7563710e2bbcc6f12",
    "requestId": "0HMIE622RD7UG:00000030",
```

**Comment by sergeyf-QA** [comment]
**Summary:**
- now for such case going to the 3rd step returns
{"status":400,"detail":"Agency contract kind unknown"}

**OK on DEV.**
