### ISSUE TITLE
Add 'clientReferenceCode' parameter to response when requesting booking information

### ISSUE THREAD

**Issue by nikolaeva31** [happy-travel/edo#1926]
Edo should return 'clientReferenceCode' parameter when booking information is requested. 

For 
```
/en/api/1.0/accommodations/bookings/refcode/{{refCode}}
/en/api/1.0/accommodations/bookings/agency
```

**Comment by sergeyf-QA** [comment]
**Summary:**
- "clientReferenceCode" is returned in response of the GET /{culture}/api/{v}/accommodations/bookings/agency and GET /{culture}/api/{v}/accommodations/bookings/refcode/{referenceCode}

**OK on DEV.**
