### ISSUE TITLE
Add 'clientReferenceCode' parameter in a booking invoice

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/edo#1933]
"clientReferenceCode" is returned in response of the GET /{culture}/api/{v}/accommodations/bookings/agency and GET /{culture}/api/{v}/accommodations/bookings/refcode/{referenceCode}

An agent can see a client ref code in invoice

**Comment by nikolaeva31** [comment]
#1935

**Comment by DenisVelinen** [comment]
Client Reference Code has been added to the invoice form in the UI and to the email.
Client Reference Code is only shown if the booking has one.

<img width="1059" alt="Снимок экрана 2022-07-05 в 22 22 34" src="https://user-images.githubusercontent.com/17127277/177400822-0367ed44-5c61-4a4e-b92f-8b089c777a3c.png">
<img width="667" alt="Снимок экрана 2022-07-05 в 22 22 50" src="https://user-images.githubusercontent.com/17127277/177400841-31019a19-20ba-4a44-801e-61e8881ea10a.png">
