### ISSUE TITLE
Add a 'clientReferenceCode' parameter to invoice

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/edo#1935]
A Methabook agent wants to see a ClientReferenceCode in a invoice

**Comment by sergeyf-QA** [comment]
@DFSko 
GET https://edo-dev.happytravel.com/en/api/1.0/accommodations/bookings/4508/supporting-documents/invoice returns "clientReferenceCode": null though in DB it exists "ClientReferenceCode"='DEV-HTL-JP-654TI5-01'
