### ISSUE TITLE
ClientReferenceCode is not passed to invoice methods

### ISSUE THREAD

**Issue by DenisVelinen** [happy-travel/edo#1948]
On https://dev.happytravel.com/

 In the DB, booking Id: 5681, ReferenceCode: DEV-HTL-AE-000KM6-01 has ClientReferenceCode: 25374592

1. Run the request https://edo-dev.happytravel.com/en/api/1.0/accommodations/bookings/5681/supporting-documents/invoice 
2. In the response, look for clientReferenceCode

Expected result:
The clientReferenceCode must have a value of 25374592 because it's in the DB.

Actual result:
The clientReferenceCode key has a value of null. 
Probably the same situation in the method of sending invoice to e-mail .../bookings/{bookingId}/supporting-documents/invoice/send

**Comment by ViTsvetkova** [comment]
@DFSko could you please check?

**Comment by ViTsvetkova** [comment]
@DenisVelinen could you please retest?

**Comment by DenisVelinen** [comment]
In the new version the invoice is generated in PDF. In this version there is no ClientReferenceCode, so there is no need for it to be present in the invoice.
