### ISSUE TITLE
Search results are returned from second request

### ISSUE THREAD

**Issue by nikolaeva31** [happy-travel/edo#1959]
1. Send a search request `/api/1.0/availabilities/searches`
```
{
  "ids": [
    "Accommodation_12004139"
  ],
  "checkInDate": "2022-09-17T00:00:00Z",
  "checkOutDate": "2022-09-24T00:00:00Z",
  "nationality": "AE",
  "residency": "AE",
  "roomDetails": [
    {
      "adultsNumber": 2,
      "childrenAges": []
    }
  ]
}
```

2. Get response 
```
{
    "searchId": "fcedd49f-cfc1-4dea-8f6f-eae22dd8371c"
}
```
3. Send next step request `/api/1.0/availabilities/searches/{{searchId}}`
4. Get response with empty accommodations
```
{
    "searchId": "fcedd49f-cfc1-4dea-8f6f-eae22dd8371c",
    "isComplete": true,
    "accommodations": []
}
```
5. Resend request with the same searchId `/api/1.0/availabilities/searches/{{searchId}}`

**AR**: Get results 

<img width="1016" alt="Screenshot 2022-07-06 at 08 50 33" src="https://user-images.githubusercontent.com/38030865/177478200-142b41a3-667f-46cb-a0df-fd4e89fd15d2.png">

**Comment by ViTsvetkova** [comment]
@nikolaeva31 @DFSko is this issue still actual?

**Comment by nikolaeva31** [comment]
> @nikolaeva31 @DFSko is this issue still actual?

Yes

**Comment by nikolaeva31** [comment]
Error wasn't reproduced on dev.
