### ISSUE TITLE
Implement a pagination of an agency booking list

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/edo#2267]
Agents should not scroll the list of bookings from more than 1 thousand objects.
Please add 20-50 bookings per page.

**Comment by alexander-plekhanov** [comment]
Implemented from frontend-only side, using Infinite scroll.

**Comment by sergeyf-QA** [comment]
**Summary:**
- implemented Infinite scroll by 30 bookings, pagination was not

**OK on DEV.**
