### ISSUE TITLE
MCN status when a supplier send us "unknown" response

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/edo#2268]
When we meet an "UNKNOWN" response from a supplier a booking status should be changed to MCN.

We want to avoid such situations:
https://happytravel.freshdesk.com/a/tickets/687

**Comment by AlexeyShok** [comment]
At the moment, we only need an implementation for the Travelgate connector.

**Comment by nikolaeva31** [comment]
In a test environment supplier doesn't return this status. 
Checked on DEV -  booking was created and canceled (on deadline and without deadline) without errors on positive flow.
