### ISSUE TITLE
Added markups are not implemented

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/edo#568]
**How to reproduce:**
- log in as any user
- try to find any booking e.g.
Jumeirah Emirates Towers, Dubai, The United Arab Emirates
29-04-2021 – 30-04-2021
1 Adult • 0 Children • 1 Room
United Kingdom of Great Britain and Northern
United Kingdom of Great Britain and Northern
- Jumeirah Emirates Towers has price 205,48
- add Agent markup for this user
- wait 5min for back-end cache
- try to find this hotel again

**Actual result:**
- price is not changed according to markup

**Expected result:**
- I should see changed price after new markup implementation

**Comment by DFSko** [comment]
try to wait about 15 minutes

**Comment by sergeyf-QA** [comment]
**Summary:**
there is no issue, markup did not work for user with 217 Id because markups were disabled for his agency.

So, OK.
