### ISSUE TITLE
PUT /{culture}​/api​/{v}​/agency may use any string in billingEmail w/o checking

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/edo#694]
**How to reproduce:**
- try to send "222" as billingEmail at PUT /{culture}​/api​/{v}​/agency

**Actual result:**
- any letters may be sent that will cause some unexpected errors in the future

**Expected result:** 
- need to check at PUT /{culture}​/api​/{v}​/agency sending is it correct entered email or not

**Comment by mingazhev** [comment]
@Raibo could you fix please?

**Comment by sergeyf-QA** [comment]
@Raibo 
1) it is possible to send empty billingEmail in endpoint
2) it is possible to send billingEmail w/o dot in domain part, e.g. 'test@testru'
3) it is possible to send billingEmail with space in acc name, e.g. 'te st@testru'

**Comment by Raibo** [comment]
Discussed this in discord and concluded that this is acceptable.

**Comment by sergeyf-QA** [comment]
**Summary:**
now it is impossible to send not valid email

**OK on DEV.**
