### ISSUE TITLE
Admin invitation/registration issue

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/edo#801]
- invite an admin on https://manage-dev.happytravel.com/admins
- proceed registration to the entering confirmation code page
- input confirmation code and try to proceed further
**Actual result:**
- I see 500 error at https://edo-dev.happytravel.com/en/api/1.0/admin/invitations/accept
**Expected result:**
- I should proceed further w/o errors

**Comment by sergeyf-QA** [comment]
@konstyefremov 
when I invite an admin on https://manage-dev.happytravel.com/admins then I see 400 error at https://edo-dev.happytravel.com/en/api/1.0/admin/invitations request 
Server Request Error

**Comment by konstyefremov** [comment]
Backend is ready, waiting for changes from frontend

**Comment by alexander-plekhanov** [comment]
On my correct request:
{
"registrationInfo":{"title":"Mr","firstName":"t1","lastName":"t2","position":"t3","email":"xfwkbwrimeaiumgfba@bptfp.com"},
"roleIds":[5]
}
server answers error 400 with no details

**Comment by alexander-plekhanov** [comment]
Also there are a small issue with "You can`t login this panel with Agent`s account" message appears when you login panel for first time.

**Comment by sergeyf-QA** [comment]
@konstyefremov 
look at Alexander's comments please

**Comment by konstyefremov** [comment]
> On my correct request:
> {
> "registrationInfo":{"title":"Mr","firstName":"t1","lastName":"t2","position":"t3","email":"[xfwkbwrimeaiumgfba@bptfp.com](mailto:xfwkbwrimeaiumgfba@bptfp.com)"},
> "roleIds":[5]
> }
> server answers error 400 with no details

fixed

**Comment by konstyefremov** [comment]
> Also there are a small issue with "You can`t login this panel with Agent`s account" message appears when you login panel for first time.

This is an another issue

**Comment by sergeyf-QA** [comment]
**Summary:**
- no 400 and 500 errors during admin invitation/registration
- invitation/registration process can be completed

**OK on DEV.**
